export type Status = 'backlog' | 'todo' | 'in-progress' | 'review' | 'done';
export type Priority = 'low' | 'medium' | 'high' | 'critical';
export type IssueType = 'task' | 'bug' | 'feature' | 'story';
export type Persona = 'general' | 'student_mit' | 'phd_researcher' | 'software_engineer' | 'politician' | 'writer' | 'freelancer' | 'upsc_aspirant';
export type Language = 'en' | 'es' | 'fr' | 'hi' | 'zh';

// Flexible Permission System
export interface CustomRole {
  id: string;
  name: string;
  color: string;
  permissions: ('create_project' | 'manage_team' | 'view_financials' | 'approve_tasks')[];
}

export type Purpose = 'learning' | 'freelancing' | 'personal' | 'startup' | 'enterprise';

export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  roleId?: string;
  role?: string;
  // Profile Fields
  is_onboarded?: boolean;
  gender?: string;
  phone?: string;
  age?: number;
  location?: string;
  country?: string;
  purpose?: Purpose;
}

export interface Organization {
  id: string;
  name: string;
  domain?: string;
  role: 'owner' | 'admin' | 'member';
}

export interface Workspace {
  id: string;
  name: string;
  
  // New Architecture Fields
  context: 'personal' | 'company';
  type: 'study' | 'project';
  organizationId?: string; // If company context
  
  // Legacy/Backwards Compat (mapped from backend)
  persona: Persona; 
  members: { userId: string; roleId: string; joinedAt: Date }[];
  customRoles: CustomRole[]; 
  
  // Enterprise Details
  companyWebsite?: string;
  location?: string;
  employeeCount?: string;
  category?: string;
  aiContextDescription?: string;
}

export interface Document {
  id: string;
  name: string;
  size: number;
  type: string;
  uploadedAt: Date;
  bucketPath: string; 
  tags: string[];
}

export interface TaskResource {
  id: string;
  type: 'link' | 'attachment';
  title: string;
  url: string;
  addedAt: Date;
}

export interface Task {
  id: string;
  workspaceId: string;
  title: string;
  description?: string;
  status: Status;
  priority: Priority;
  assignee?: string;
  assigneeId?: string;
  estimatedHours?: number;
  isDailyFocus?: boolean;
  resources?: TaskResource[];
  // Jira-style
  dueDate?: string;        // ISO string
  labels?: string[];
  issueType?: IssueType;
}

export interface Company {
    id: string;
    workspaceId: string;
    name: string;
    mission: string;
    color: string;
    projects: Project[];
}

export interface Project {
  id: string;
  workspaceId: string;
  name: string;
  type: 'build' | 'learning' | 'client' | 'research' | 'campaign';
  mission?: string;
  tasks: Task[];
  progress: number; 
}

export interface Note {
  id: string;
  workspaceId: string;
  contextId?: string;
  content: string;
  type: 'general' | 'idea';
  color: string;
  visibility?: 'private' | 'public' | 'team';
  ownerId?: string;
  createdAt: Date;
}

export interface CalendarEvent {
  id: string;
  workspaceId: string;
  ownerId?: string;
  title: string;
  start: string; // ISO String often better for serializing, but we will cast to Date in frontend services
  end: string;
  type: 'block' | 'meeting' | 'personal' | 'task_block';
  scope: 'personal' | 'workspace' | 'company';
  taskId?: string;
  color: string;
  isAutoGenerated?: boolean;
}
