"""add calendar recurrence timezone attendees organization_id

Revision ID: 49c02f01de53
Revises: 545e8d25f25f
Create Date: 2026-08-05 00:23:26.864014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49c02f01de53'
down_revision = '545e8d25f25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_rule', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_parent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key('fk_calendar_events_organization_id', 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_calendar_events_recurrence_parent_id', 'calendar_events', ['recurrence_parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_recurrence_parent_id', type_='foreignkey')
        batch_op.drop_constraint('fk_calendar_events_organization_id', type_='foreignkey')
        batch_op.drop_column('attendees')
        batch_op.drop_column('recurrence_parent_id')
        batch_op.drop_column('recurrence_rule')
        batch_op.drop_column('timezone')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
