"""add module generation marketplace tables

Revision ID: 545e8d25f25f
Revises: 8cb7513702a4
Create Date: 2026-08-04 23:27:12.070985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '545e8d25f25f'
down_revision = '8cb7513702a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('current_version_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('module_template_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_template_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('generation_status', sa.String(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('critique_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_template_id'], ['module_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_template_id', 'version', name='uq_module_template_version')
    )
    op.create_table('module_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_template_id', sa.String(), nullable=False),
    sa.Column('module_template_version_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_template_id'], ['module_templates.id'], ),
    sa.ForeignKeyConstraint(['module_template_version_id'], ['module_template_versions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # module_templates.current_version_id references module_template_versions, which is
    # created above this line but after module_templates — deferred via ALTER TABLE
    # rather than an inline FK, matching the model's use_alter=True.
    with op.batch_alter_table('module_templates', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_module_templates_current_version_id', 'module_template_versions',
            ['current_version_id'], ['id'],
        )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_instance_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_module_instance_id', 'module_instances', ['module_instance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_module_instance_id', type_='foreignkey')
        batch_op.drop_column('module_instance_id')

    with op.batch_alter_table('module_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_module_templates_current_version_id', type_='foreignkey')

    op.drop_table('module_instances')
    op.drop_table('module_template_versions')
    op.drop_table('module_templates')
    # ### end Alembic commands ###
